DROP TABLE EMPLOYEES;
/
DROP TABLE MANAGER;
/
DROP TABLE R_REQUEST;
/
CREATE TABLE EMPLOYEES(
EMPLOYEES_ID INTEGER PRIMARY KEY,
FIRSTNAME VARCHAR2(30),
LASTNAME VARCHAR2(30),
USERNAME VARCHAR2(30),
PASSWORD VARCHAR2(30),
EMAIL VARCHAR2(30),
MANAGER_CLASS_ID INTEGER
);
/
CREATE SEQUENCE EMPSEQ;
/
CREATE TABLE MANAGER (
MANAGER_ID INTEGER PRIMARY KEY,
FIRSTNAME VARCHAR2(30),
LASTNAME VARCHAR2(30),
USERNAME VARCHAR2(30),
PASSWORD VARCHAR2(30),
EMAIL VARCHAR2(30)
);
/
CREATE SEQUENCE MANSEQ;
/
CREATE TABLE R_REQUEST (
REQUEST_ID INTEGER PRIMARY KEY,
EMPLOYEES_ID INTEGER NOT NULL,
R_DATE VARCHAR2(30),
R_DESCRIPTION VARCHAR(30),
R_COST NUMERIC(8,2)
);
/
CREATE SEQUENCE REQSEQ;
/
ALTER TABLE R_REQUEST 
ADD CONSTRAINT FK_R_REQUEST_EMPLOYEES_ID
FOREIGN KEY (EMPLOYEES_ID) REFERENCES EMPLOYEES(EMPLOYEES_ID);
/


